### ISSUE TITLE
func isValid tá pedindo o segundo param sendo q é opcional

### ISSUE THREAD

**Issue by nelsera** [carvalhoviniciusluiz/cpf-cnpj-validator#12]
![isValid](https://user-images.githubusercontent.com/6188074/81454368-7260f200-9162-11ea-8b42-40e08f9675a7.png)

**Comment by carvalhoviniciusluiz** [comment]
bem estranho, irei verificar!

**Comment by vigoru** [comment]
O mesmo ocorreu aqui comigo.

**Comment by carvalhoviniciusluiz** [comment]
irei investigar por que, na teoria esta como não obrigatório
https://github.com/carvalhoviniciusluiz/cpf-cnpj-validator/blob/deb38a5d8370d8379cbada9df0bc54b3378c6c88/src/cpf.ts#L22

**Comment by satheler** [comment]
Também acontece o mesmo comigo.

**Comment by carvalhoviniciusluiz** [comment]
Alguém monta um projeto test apresentando esse problema, tentei simular mas não peguei nada

**Comment by satheler** [comment]
**cpf.d.ts**
```typescript
declare const _default: {
    verifierDigit: (digits: any) => number;
    strip: (number: any, strict: any) => any;
    format: (number: any) => any;
    isValid: (number: any, strict: any) => boolean;
    generate: (formatted: any) => any;
};
export default _default;
```
![image](https://user-images.githubusercontent.com/6925493/82851950-ce07db00-9ed7-11ea-8154-85579e4bf861.png)

==== ==== ====

**cnpj.d.ts**
```typescript
declare const _default: {
    verifierDigit: (digits: any) => number;
    strip: (number: any, strict: any) => any;
    format: (number: any) => any;
    isValid: (number: any, strict: any) => boolean;
    generate: (formatted: any) => any;
};
export default _default;
```
![image](https://user-images.githubusercontent.com/6925493/82851958-d7914300-9ed7-11ea-8381-f650a6fa77f2.png)

**Comment by carvalhoviniciusluiz** [comment]
Problema estava na criação automática de arquivos `.d.ts` 🤦  valeu @satheler pelos prints
Atualizem e vejam se resolveu..

**Comment by satheler** [comment]
Atualizado para a versão 1.0.2 e funcionou 100%!!!
