### ISSUE TITLE
Add type definitions for TypeScript

### ISSUE THREAD

**Issue by satheler** [carvalhoviniciusluiz/cpf-cnpj-validator#13]
It'd be great if this project add a declaration file to https://github.com/DefinitelyTyped/DefinitelyTyped so that it can be used with TypeScript.

**Comment by rbbernardino** [comment]
@satheler Why did you close the issue? Have you solved it? How?

**Comment by satheler** [comment]
> @satheler Why did you close the issue? Have you solved it? How?

@rbbernardino this repository is already written in Typescript. However, when using the functions of this repository, the  type-checking does not reflect what was written.
