### ISSUE TITLE
Mover dependencia @hapi/joi para seção "peerDependencies"

### ISSUE THREAD

**Issue by leandrogehlen** [carvalhoviniciusluiz/cpf-cnpj-validator#22]
Analisando o repositório as rotinas não utilizam a dependência `@hapi/joi`, 
apenas a rotinas de testes fazem uso desta biblioteca.

Sugiro mover essa dependência para a sessão `devDependencies`

**Comment by carvalhoviniciusluiz** [comment]
No passado essa lib ficava em devdependencies mas alguns devs relataram problemas ou algum tipo de inconsistência por isso movi para dependencies.

**Comment by leandrogehlen** [comment]
Eu movi para `peerDependencies` assim quem usar a dependencia `@hapi/joi` deve instalar no seu projeto.
Outra solução seria criar outro repositorio `cpf-cnpj-joi` que possui como dependencia `cpf-cnpj-validator`

**Comment by leandrogehlen** [comment]
Outro problema que vi agora é que [@hapi/joi](https://www.npmjs.com/package/@hapi/joi) está `deprecated`.
Vou modificar o PR para utilizar a dependencia `joi`
