### ISSUE TITLE
Unformat function

### ISSUE THREAD

**Issue by IncognitaDev** [carvalhoviniciusluiz/cpf-cnpj-validator#24]
I think this module can contain a unformat function to remove dots and others non number characters.

**Comment by carvalhoviniciusluiz** [comment]
yes it can be interesting

**Comment by carvalhoviniciusluiz** [comment]
already exists,

```js
import { cpf } from 'cpf-cnpj-validator'; 

const num = cpf.generate();
// #=> 25634428777
 
cpf.format(num); // <----- here!! 
// #=> 256.344.287-77
```

**Comment by IncognitaDev** [comment]
this function aplly format, I sugested a function that removes format

**Comment by carvalhoviniciusluiz** [comment]
I understand, this is an accessory feature. A very simple regex can be used to test.
```js
const removeMask = (value) => {
  return value && value.replace(/[^\w\s]/gi, '')
}

removeMask('725.428.702-72')
// #=> "72542870272"

removeMask('33.057.042/0001-00')
// #=> "33057042000100"
```

but in this case we are removing all special characters and it could also be any string.

Should we leave the treatment open for any string or, treat only number of valid documents to have a more specific regex?

**Comment by carvalhoviniciusluiz** [comment]
I found the idea interesting, I'll check the best way to add it...

I'm ending this problem for now
