### ISSUE TITLE
Retorno True valid CPF e CNPJ com letras

### ISSUE THREAD

**Issue by rodrigoPQF** [carvalhoviniciusluiz/cpf-cnpj-validator#30]
Opa beleza,

Está validando um CPF por exemplo (56051d349065), como true

`
{
    "document": "56051d349065",
}
`
`
  let isValidCPF =  cpf.isValid(document)
//isValidCPF = true
`

O que eu fiz para mudar
`
document.replace(/\D/g, '0')
`

**Comment by carvalhoviniciusluiz** [comment]
sobe uma pr e verifica se fica direitinho nos tests
