### ISSUE TITLE
Can't resolve 'module joi' 

### ISSUE THREAD

**Issue by MallikaG** [carvalhoviniciusluiz/cpf-cnpj-validator#4]
I have installed as "npm i cpf-cnpj-validator" and I got the error as ---

./node_modules/cpf-cnpj-validator/dist/cpf-cnpj-validator.es.js
Module not found: Can't resolve 'joi' in '/node_modules/cpf-cnpj-validator/dist'

Then I tried to install joi as "npm install joi", and  got below error

AssertionError: Must be invoked on a Joi instance.

push../node_modules/joi/lib/index.js.internals.callWithDefaults
node_modules/joi/lib/index.js:32
root.string
node_modules/joi/lib/index.js:94
Module../node_modules/cpf-cnpj-validator/dist/cpf-cnpj-validator.es.js
node_modules/cpf-cnpj-validator/dist/cpf-cnpj-validator.es.js:138

Please guide me to resolve this issue.

**Comment by carvalhoviniciusluiz** [comment]
make sure the update that fixes your issue

**Comment by MallikaG** [comment]
I have taken the updated cpf-cnpj-validator , and I get below issue 

AssertionError: Must be invoked on a Joi instance.
▼ 3 stack frames were expanded.
push../node_modules/@hapi/joi/lib/index.js.internals.callWithDefaults
node_modules/@hapi/joi/lib/index.js:29
root.string
node_modules/@hapi/joi/lib/index.js:91
Module../node_modules/cpf-cnpj-validator/dist/cpf-cnpj-validator.es.js
node_modules/cpf-cnpj-validator/dist/cpf-cnpj-validator.es.js:138

**Comment by carvalhoviniciusluiz** [comment]
the tests are passing, which is very strange.
I need you to send me an example simulating this error so you can check.
